version: "3"

# Since avalanche use IPv6, we need to turn on ipv6 for docker
# 1. Add the following lines to daemon configuration
# {
#    "fixed-cidr-v6": "fd00::/80",
#    "ipv6": true,
# }
#

services:
  l1_chain:
    image: bobanetwork/avalanche:latest
    container_name: l1_chain
    build:
      context: ./docker
      dockerfile: Dockerfile.avalanche
    ports:
      # expose the service to the host for integration testing
      - "9650:9650"
      - "9652:9652"
      - "9654:9654"
      - "9656:9656"
      - "9658:9658"
    networks:
      - ava-network

networks:
  ava-network:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd00:1::/64"
          # gateway: "fd00:1::1"
